apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
spec:
  selector:
    matchLabels:
      app: tripviewer-pod
  template:
    metadata:
      labels:
        app: tripviewer-pod
    spec:
      containers:
      - name: tripviewer-container
        image: registryqaz7211.azurecr.io/tripinsights/tripviewer:1.0
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile-service.default.svc.cluster.local:80"
        - name: TRIPS_API_ENDPOINT
          value: "http://trips-service.default.svc.cluster.local:80"
        - name: BING_MAPS_KEY
          value: ""
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
spec:
  selector:
    app: tripviewer-pod
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
