apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-deployment
spec:
  selector:
    matchLabels:
      app: user-java-pod
  template:
    metadata:
      labels:
        app: user-java-pod
    spec:
      hostname: user-java-container 
      containers:
      - name: user-java-container
        image: registryqaz7211.azurecr.io/tripinsights/user-java:1.0
        env:
        - name: PORT
          value: "80"
        - name: SQL_USER
          value: "sqladminqAz7211"
        - name: SQL_PASSWORD
          value: "kF3yk5Qp3"
        - name: SQL_SERVER
          value: "sqlserverqaz7211.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-java-service
spec:
  selector:
    app: user-java-pod
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
