apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-deployment
spec:
  selector:
    matchLabels:
      app: user-java-pod
  template:
    metadata:
      labels:
        app: user-java-pod
    spec:
      containers:
      - name: user-java-container
        image: registryqaz7211.azurecr.io/tripinsights/user-java:1.0
        env:
        - name: PORT
          value: "80"
        - name: SQL_USER
          value: "sqladminqAz7211"
        - name: SQL_PASSWORD
          value: "kF3yk5Qp3"
        - name: SQL_SERVER
          value: "sqlserverqaz7211.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  
spec:
  selector:
    app: poi-pod
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer
