apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deployment
  namespace: api
spec:
  selector:
    matchLabels:
      app: trips-pod
  template:
    metadata:
      labels:
        app: trips-pod
    spec:
      containers:
      - name: trips-container
        image: registryqaz7211.azurecr.io/tripinsights/trips:1.0
        env:
        - name: SQL_USER
          value: "sqladminqAz7211"
        - name: SQL_PASSWORD
          value: "kF3yk5Qp3"
        - name: SQL_SERVER
          value: "sqlserverqaz7211.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"        
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: trips-service
  namespace: api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  
spec:
  selector:
    app: trips-pod
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
