apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: api
spec:
  selector:
    matchLabels:
      app: poi-pod
  template:
    metadata:
      labels:
        app: poi-pod
    spec:
      containers:
      - name: poi-container
        image: registryqaz7211.azurecr.io/tripinsights/poi:1.0
        env:
        - name: WEB_SERVER_BASE_URI
          value: "http://0.0.0.0"
        - name: WEB_PORT
          value: "8080"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"          
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080        
        volumeMounts:
        - name: keyvault
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: keyvault
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: kvcreds
          options:
            keyvaultname: "T1VeyVault"
            keyvaultobjectnames: "SQLUSER;SQLPASSWORD;SQLSERVER;SQLDBNAME"
            keyvaultobjecttypes: "secret;secret;secret;secret"
            keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER;SQL_DBNAME"
            resourcegroup: "teamResources"
            subscriptionid: 91ae9c19-2591-4c54-9c4a-4bb90338d474
            tenantid: "e12892b6-7862-42d2-9e6f-c36d23a32018"
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  
spec:
  selector:
    app: poi-pod
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
