apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
spec:
  selector:
    matchLabels:
      app: userprofile-pod
  template:
    metadata:
      labels:
        app: userprofile-pod
    spec:
      containers:
      - name: userprofile-container
        image: registryqaz7211.azurecr.io/tripinsights/userprofile:1.0
        env:
        - name: PORT
          value: "8080"
        - name: SQL_USER
          value: "sqladminqAz7211"
        - name: SQL_PASSWORD
          value: "kF3yk5Qp3"
        - name: SQL_SERVER
          value: "sqlserverqaz7211.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"  
spec:
  selector:
    app: userprofile-pod
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
